[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "db",
    "logger",
]

[tool.uv.sources]
logger = { workspace = true }
db = { workspace = true }
